# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TTXMLY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'SnapKit', '~> 5.0.0'
  pod 'Moya', '~> 14.0.0-alpha.1'
  pod 'ESTabBarController-swift', '~> 2.7'
  pod 'ESPullToRefresh', '~> 2.9'
  pod 'HandyJSON', '~> 5.0.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Kingfisher', '~> 5.6.0'
  # 播放网络音频
  pod 'StreamingKit', '~> 0.1.30'
  pod 'SwiftMessages', '~> 7.0.0'

  target 'TTXMLYTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
