source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'TTXMLY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'SnapKit'
  pod 'Moya', '~> 14.0.0-alpha.1'
  # TabBar 样式
  pod 'ESTabBarController-swift'
  pod 'ESPullToRefresh'
  pod 'HandyJSON'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  # 播放网络音频
  pod 'StreamingKit'
  # 消息提示
  pod 'SwiftMessages'
  
  # 跑马灯
  pod 'JXMarqueeView'
  # 滚动页
  pod 'LTScrollView'
  # banner滚动图片
  pod 'FSPagerView'
  # 分页
  pod 'DNSPageView', '2.1.0'
  # HUD
  pod 'SVProgressHUD'

  target 'TTXMLYTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
